server:
  port: 8400

spring:
  application:
    name: ldx-goods
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: happy
    url: jdbc:mysql://127.0.0.1:3307/wfw_goods?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7000/eureka
